# Site settings
title: Om Shankara
email: info@omshankara.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://www.omshankara.com

# Default language
lang: en

languages:
  en: English
  es: Español

# Color settings (hex-codes with the leading hash-tag)
color:
  theme-main: '#06a9d6'
  primary-text: '#000'
  lighter-text: '#fff'
  primary-bg: '#fff'
  links: '#06a9d6'
  links-hover: '#15b8e4'
  icons: '#fff'

# Head settings
home_text_1: 
home_text_2: Shankara

# Google maps
map:
  api_key: AIzaSyAOoTRdEUmyIGq8p2zVNqAa8-n1VEtFs5s
  marker_lat: "-33.8748269"
  marker_lng: "151.2227222"
  center_lat: "-33.8704491"
  center_lng: "151.2048432"
  zoom: 15

# Google analytics
tracking_id: "UA-85978390-1"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social: []
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty


# Translations
t:
  en:
    description: > # this means to ignore newlines
      Rolfing® Structural Integration and Yoga in Sydney. If you have any questions or comments send an email to info@omshankara.com. I'm located in the heart of Sydney.
    intro:
      - Rolfing & Yoga in Sydney

    menu_yoga: Yoga
    menu_rolfing: Rolfing
    menu_about: About
    menu_contact: Contact

    title_about: About me
    title_contact: Contact

    misc:
      read_more: "Read more"
      read_less: "Read less"

    yoga:
      title: "Yoga is what happens to you, not what you do" # not used
      content_intro:
        - "Yogestalt is the type of Yoga that I practice, study and teach, and is the name given to the practice of various forms of Yoga in the light of Gestalt therapy. Practice through which a process of transformation starts, in which opposites, as well as the tension between them, become apparent. This allows us to know and integrate the opposites in ourselves."
        - "The practice guides us in finding our innate potential, starting the journey towards our own center, regaining the ability to trust ourselves. This experience, which is unique, diverse and personal, strengthens our confidence in the resources available to us, helping us live in a genuine way, free of conditionings."
      content_collapse:
        - "Some of the opposites we try to integrate are: flexibility and rigidity, strength and weakness, contraction and expansion, dispersal and concentration, fantasy and reality, lack and presence, discomfort and comfort, what’s open and what’s closed, what’s free and what’s oppressed, pain and pleasure, apathy and vitality, courage and shame, what’s rejected and what’s accepted, anger and serenity, joy and sorrow, anguish and relief, restlessness and peace, fear and love."
        - "During the practice, different ways of breathing are explored, as well as various forms of stretching and strengthening. We also attempt to generate, in various different ways, stimuli on the organic and energetic aspects, and to deepen the contemplative aspect by using sound vibrations and symbolic gestures. Finally, we aim for the integration of our oneiric and vigil worlds. Always with the intention of being present, putting into practice the contemplative aspect that yoga offers to deepen the perception of the here and now; contemplating and observing ourselves, as proposed by the Gestalt therapy, in a non-interpretative and essentially descriptive way, focusing on what is being perceived and felt here and now. This subjective perception is essential, and invites the practitioner to trust what he feels, rediscovering organic ways of practicing, which frees the roads that connect our bodily, emotional, mental and intuitive aspects."

      content_footer:
        - "If you want to schedule a class, <a href='https://thrivehealth.cliniko.com/bookings' target='_blank'>book now!</a> If you have questions, <a href='#contact'>contact me</a>."

    rolfing:
      title: "Rolfing Structural Integration" # not used
      content_intro:
        - "" # Extra empty paragraph for better visualization
        - "Rolfing® Structural Integration can significantly improve your body‘s structure, posture and movement by releasing accumulated tensions and strains through a process involving soft tissue manipulation and movement education."
        - "Rolfing can help athletes, dancers, actors, musicians, yoga and martial arts practitioners, or anyone wishing to improve their body awareness and physical performance. As well as people of all ages with histories of pain and discomfort, and anyone hoping to rediscover freedom and ease of movement."

      content_collapse:
        - "Rolfing Structural Integration, originally developed by Dr. Ida Rolf, PhD, is based on the premise that the quality of life and well-being depend in part on the person’s capacity to adapt to the field of gravity. Rolfing is an approach to helping the person live and function with greater ease, grace and efficiency in the field of gravity. In particular, Rolfing helps us use gravity as an ally in the manifestation of the human upright posture, as well as in the uniquely human activities and place in the world that uprightness permits."       
        - "Rolfers™ work with the body’s soft tissue, specifically connective tissue called fascia. Fascia gives muscles, organs and the human body support and their characteristic shape, and since it's highly enervated it's key to perception, posture, coordination and movement. A Rolfer uses their unique quality of touch during a series of sessions that engage the entire body in a very precise way, while also inviting client participation through movement. Working together, Rolfer and client seek to encourage new postural and movement patterns that are more comfortable and efficient – resolving pain and discomfort, adding ease and grace to every client’s life."
        - "Rolfing works, because it initiates structural changes that restore the entire body to a more natural order. The body’s inherent capacity to adapt relaxes, corrects and integrates misalignments and imbalances. This allows posture and movement patterns to adjust towards their most efficient and at-ease form, freeing restrictions, alleviating pain, and building a foundation for lasting and sustainable results. Moreover, as the body changes physically, significant shifts in perception occur as well, resulting in lowered stress and anxiety, increased confidence and maturing emotional expression."
        - "Sessions are usually between 60 and 90 minutes long. This varies because the important aspect here is not the duration but the accomplishment of the specific session's goals. Ida P. Rolf designed a basic strategy to deliver Rolfing as a series of 10 sessions. Generally, but not necessarily, a client's initial Rolfing series is based on this formal 10-sessions strategy. However, the number of sessions and precise content of each is determined by the client's needs and best interests."
      content_footer:
        - "If you want to schedule a session, <a href='https://thrivehealth.cliniko.com/bookings' target='_blank'>book now!</a> If you have questions, <a href='#contact'>contact me</a>."

    content_about:
      - "My name is Celeste, I'm from Argentina and I live in Sydney. I started practicing yoga in 2009, and it fascinated me from the very first moment; from then on I kept practicing and discovering different schools. I practiced Hatha yoga in Mendoza, and Iyengar and Swasthya yoga in Buenos Aires, and in 2012 I received the certification as Yoga instructor from the Yoga Kai Institute, in Buenos Aires, Argentina. During that year, I also practiced Yogestalt for the very first time, and I felt that I had finally found what I was looking for. This way of practicing totally changed my view and understanding of Yoga, and I decided to do the Yogestalt training course with my teacher, Ricardo Risso Patron, in 2013, in Buenos Aires, Argentina. Since then I am studying with him, practicing, learning, deepening my knowledge and understanding."
      - "I discovered Rolfing by chance in 2013, while reading a book on Gestalt therapy. I was instantly drawn to it, and I decided to see what it was all about. I started reading a about it, and taking Rolfing sessions. What a  wonderful discovery! I was so interested in it that I decided to start studying in the European Rolfing Association, in Munich, Germany, where I completed my training as a Certified Rolfer."
      - "My wish is to help others, with the tools that these two practices have given me, and to share the integrating vision that both have in common."

    content_contact:
      - "If you want to schedule a Rolfing session or a Yoga class, <a href='https://thrivehealth.cliniko.com/bookings' target='_blank'>book now!</a> If you have any questions or comments, fill in the contact form below. Or just send an email to <a href='mailto:info@omshankara.com'>info@omshankara.com</a>. I'm located in the heart of Sydney, Australia."

    contact_form:
      name: Name
      email: Email
      question: Question
      subject: Enquiry OmShankara.com
      submit: Submit
      submit_ok_title: "Thank you!"
      submit_ok_text: "Your enquiry was sent successfully, I'll contact you shortly."
      submit_fail_title: "Oops!"
      submit_fail_text: "Your enquiry could not be sent, try again later or send me an email to <a href='mailto:info@omshankara.com'>info@omshankara.com</a>."
      submit_close_button: "OK"

  es:
    description: > # this means to ignore newlines
      Rolfing® Integración Estructural y Yoga en Sydney. Si tenés preguntas y querés conocer más, escribime a info@omshankara.com. Estoy ubicada en el corazón de Sydney.

    intro:
      - Rolfing y Yoga en Sydney

    menu_yoga: Yoga
    menu_rolfing: Rolfing
    menu_about: Acerca
    menu_contact: Contacto

    title_about: Acerca de mi
    title_contact: Contacto

    misc:
      read_more: "Leer más"
      read_less: "Leer menos"

    yoga:
      title: "Yoga es lo que te pasa, no lo que hacés" # not used
      content_intro:
        - "Yogestalt es el tipo de Yoga que yo practico, estudio y enseño, y es el nombre que recibe la práctica de las diversas formas de Yoga bajo la luz de la Terapia Gestalt. Práctica a través de la cual se inicia un proceso de transformación en el que los opuestos se hacen presentes, así como también la tensión que existe entre ellos. Esto nos permite conocer e integrar los opuestos en nosotros mismos. "
        - "La práctica nos lleva a que nos encontremos con nuestro potencial innato, iniciando nuestro viaje hacia nuestro propio centro, recuperando la posibilidad de apoyarnos en nosotros mismos. Esta experiencia, que es única, diversa y personal, fortalece nuestra confianza en los recursos de los que disponemos como personas, intentando vivir de una manera auténtica y libre de condicionamientos."
      content_collapse:
        - "Algunos de los opuestos que intentamos integrar son la flexibilidad con la rigidez, la fuerza con la debilidad, la contracción con la ampliación, la dispersión con la concentración, la fantasía con la realidad, la ausencia con la presencia, la incomodidad con la comodidad, lo abierto con lo cerrado, lo oprimido con lo liberado, el dolor con el placer, la apatía con la vitalidad, la vergüenza con el coraje, lo rechazado con lo aceptado, la ira con la serenidad, la alegría con la tristeza, la angustia con el alivio, la intranquilidad con la tranquilidad, el miedo con el amor."
        - "En la práctica se proponen diferentes maneras de respirar, y se invita a descubrir y experimentar diversas formas de estirarse y fortalecerse, a practicar variadas maneras de generar estímulos sobre el aspecto orgánico y energético, a profundizar el aspecto contemplativo, a usar vibraciones sonoras, a profundizar en gestos simbólicos, y a integrar el mundo onírico con el de la vigilia. Siempre con la intención de estar presente, poniendo en práctica el aspecto contemplativo que el Yoga ofrece para profundizar en el aquí-ahora; contemplándonos, como propone la Terapia Gestalt, de forma esencialmente descriptiva, no interpretativa, poniendo el foco sobre lo que se está percibiendo y sintiendo en el momento. Esta percepción subjetiva es fundamental, e invita al practicante a que confíe en lo que siente, redescubriendo formas orgánicas de practicar, que liberan los caminos que conectan nuestro aspecto corporal, con el emocional, con el mental y el intuitivo."

      content_footer:
        - "Si te interesa agendar una clase, <a href='https://thrivehealth.cliniko.com/bookings' target='_blank'>reservá ahora!</a> Si tenés preguntas, <a href='#contact'>contactame</a>."

    rolfing:
      title: "Rolfing Integración Estructural" # not used
      content_intro:
        - "" # Extra empty paragraph for better visualization
        - "Rolfing® Integración Estructural puede mejorar significativamente la estructura de tu cuerpo, la postura y los movimientos por medio de la liberación de tensiones acumuladas y de restricciones, a través de un proceso que implica manipulación del tejido conectivo y educación de movimiento."
        - "Rolfing puede ayudar a los atletas, bailarines, actores, músicos, practicantes de yoga y de artes marciales, o cualquier persona que desee mejorar la conciencia corporal y el rendimiento físico. Así como personas de todas las edades con historias de dolor y malestar, y cualquier persona con el deseo de redescubrir la libertad y facilidad de movimiento."

      content_collapse:
        - "Rolfing Integración Estructural, originalmente desarrollado por la Dra. Ida Rolf, PhD, se basa en la premisa de que la calidad de vida y el bienestar dependen en parte de la capacidad de la persona para adaptarse al campo de gravedad. Rolfing es un enfoque para ayudar a la persona a vivir con mayor facilidad, gracia y eficiencia en el campo de la gravedad. En particular, Rolfing nos ayuda a utilizar la gravedad como un aliado en la manifestación de la postura erguida, así como en nuestras actividades."
        - "Los Rolfers, trabajan con los tejidos blandos del cuerpo, específicamente el tejido conectivo llamado fascia. Este tejido brinda apoyo a nuestros músculos, órganos y a todo nuestro cuerpo, dándole también su forma característica. Al ser altamente enervado, es clave para la percepción, la postura, la coordinación y el movimiento. Los Rolfers utilizan su calidad única de tacto durante una seria de sesiones que involucran a todo el cuerpo de una manera muy precisa, a la vez que alientan la participación activa del cliente a través de distintos movimientos. Trabajando juntos, el Rolfer y el cliente tratan de fomentar nuevos patrones posturales y de movimiento, que sean más cómodos y eficientes  aliviando así el dolor y el malestar, añadiendo facilidad y gracia a la vida diaria del cliente."
        - "Rolfing funciona ya que inicia cambios estructurales que tienden a restaurar el orden natural del cuerpo. La capacidad inherente del cuerpo para adaptarse relaja, corrige y permite la integración de dichos desajustes y desequilibrios. Esto permite que los patrones de postura y movimiento se ajusten hacia su forma más eficiente y cómoda, liberando restricciones, aliviando el dolor, y construyendo las bases para resultados duraderos y sostenibles. Por otra parte, ya que el cuerpo cambia físicamente, ocurren cambios significativos en la percepción, lo que resulta en una disminución del estrés y de la ansiedad, y un aumento en la confianza y la expresión emocional madura."
        - "La duración de cada sesión es de entre 60 y 90 minutos. Esto varía debido a que el aspecto principal no es dicha duración, sino el logro del objetivo especifico de la sesión. Ida P. Rolf diseñó una estrategia básica aplicar Rolfing a través de una serie de 10 sesiones. En general, pero no necesariamente, la serie inicial de Rolfing de un cliente se basa en esta estrategia formal de 10 sesiones. Sin embargo, el número y contenido preciso de cada una está determinada por las necesidades del cliente."      
      content_footer:
        - "Si te interesa agendar una sesión, <a href='https://thrivehealth.cliniko.com/bookings' target='_blank'>reservá ahora!</a> Si tenés preguntas, <a href='#contact'>contactame</a>."

    content_about: 
      - "Mi nombre es Celeste, soy Argentina y vivo en Sydney. Empecé a practicar Yoga en el año 2009, y me fascinó desde el primer momento; desde ahí seguí practicando constantemente, descubriendo distintas escuelas. Hice Hatha yoga en Mendoza, Iyengar y Swasthya yoga en Buenos Aires, y en el año 2012 recibí la certificación como instructora de Yoga por parte del Instituto Yoga Kai, de Buenos Aires, Argentina. En el mismo año hice mi primera práctica de Yogestalt, y sentí que por fin había encontrado lo que estaba buscando. Esta manera de practicar cambió totalmente mi visión y comprensión del Yoga, y decidí hacer el curso de formación en Yogestalt con mi profesor, Ricardo Risso Patrón, en el año 2013, en Buenos Aires, Argentina. Desde entonces que estoy estudiando con él, practicando, aprendiendo, profundizando."
      - "Al Rolfing lo descubrí de casualidad, en el año 2013, mientras leía un libro sobre terapia Gestalt. Me interesó de inmediato, y decidí ver de qué se trataba, así que empecé a leer un poco sobre el tema, y a tomar sesiones de Rolfing. Que descubrimiento tan maravilloso! Quedé tan enganchada que decidí empezar a estudiar en la Asociación Europea de Rolfing (European Rolfing Association), en Munich, Alemania, donde completé mi formación como Rolfer certificada."
      - "Mi deseo es ayudar a otras personas, a partir de las herramientas que me han brindado estas dos prácticas, y poder compartir la visión integradora que ambas proponen."

    content_contact:
      - "Si querés agendar una sesión de Rolfing o una clase de Yoga, <a href='https://thrivehealth.cliniko.com/bookings' target='_blank'>reservá ahora!</a> Si tenés preguntas y querés conocer más, completá el formulario con tu consulta. O escribime directamente a <a href='mailto:info@omshankara.com'>info@omshankara.com</a>. Estoy ubicada en el corazón de Sydney, Australia."

    contact_form:
      name: Nombre
      email: Email
      question: Consulta
      subject: Consulta OmShankara.com
      submit: Enviar
      submit_ok_title: "Gracias!"
      submit_ok_text: "Tu consulta fue enviada exitosamente, me pondré en contacto a la brevedad."
      submit_fail_title: "Disculpá"
      submit_fail_text: "No se pudo enviar tu consulta, intentá nuevamente o escribime a <a href='mailto:info@omshankara.com'>info@omshankara.com</a>."
      submit_close_button: "OK"
